/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package manydice;

import javax.swing.JFrame;
import static manydice.Dice.animate;
import static manydice.Dice.numrolled;
import static manydice.Dice.roll;

/**
 *
 * @author 802709
 */
public class Window extends javax.swing.JFrame {

    //private static int numrolled;
//    private static int numsides;
    private static int ticks;
    
    public static boolean d4isrolling;
    public static boolean d6isrolling;
    public static boolean d8isrolling;
    public static boolean d10isrolling;
    public static boolean percentileisrolling;
    public static boolean d12isrolling;
    public static boolean d20isrolling;

    
    /**
     * Creates new form Window
     */
    public Window() {
        initComponents();
        d4isrolling = true;
        d6isrolling = true;
        d8isrolling = true;
        d10isrolling = true;
        percentileisrolling = true;
        d12isrolling = true;
        d20isrolling = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        d4 = new javax.swing.JButton();
        d6 = new javax.swing.JButton();
        d8 = new javax.swing.JButton();
        d10 = new javax.swing.JButton();
        percentileDie = new javax.swing.JButton();
        d12 = new javax.swing.JButton();
        d20 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputBox = new javax.swing.JTextArea();

        jButton5.setText("jButton5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        d4.setText("Roll D4");
        d4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d4ActionPerformed(evt);
            }
        });

        d6.setText("Roll D6");
        d6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d6ActionPerformed(evt);
            }
        });

        d8.setText("Roll D8");
        d8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d8ActionPerformed(evt);
            }
        });

        d10.setText("Roll D10");
        d10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d10ActionPerformed(evt);
            }
        });

        percentileDie.setText("Roll Percentile");
        percentileDie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                percentileDieActionPerformed(evt);
            }
        });

        d12.setText("Roll D12");
        d12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d12ActionPerformed(evt);
            }
        });

        d20.setText("Roll D20");
        d20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d20ActionPerformed(evt);
            }
        });

        outputBox.setColumns(20);
        outputBox.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        outputBox.setRows(1);
        outputBox.setTabSize(4);
        outputBox.setBorder(null);
        jScrollPane1.setViewportView(outputBox);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(percentileDie)
                        .addGap(18, 18, 18)
                        .addComponent(d12)
                        .addGap(18, 18, 18)
                        .addComponent(d20)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(d4)
                        .addGap(18, 18, 18)
                        .addComponent(d6)
                        .addGap(18, 18, 18)
                        .addComponent(d8)
                        .addGap(18, 18, 18)
                        .addComponent(d10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(d4)
                        .addComponent(d6)
                        .addComponent(d8)
                        .addComponent(d10))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(percentileDie)
                    .addComponent(d12)
                    .addComponent(d20))
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void d4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d4ActionPerformed
         int numsides = 4;
        // evt.equals(numrolled);
            roll(numsides);
            outputBox.setText("" + numrolled);
            animate(D4.ii, D4.img, "/images/d4animated.gif" );
            d4isrolling = true;
    }//GEN-LAST:event_d4ActionPerformed

    private void d6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d6ActionPerformed
            int numsides = 6;
            roll(numsides);
            outputBox.setText("" + numrolled);
            animate(D6.ii, D6.img, "/images/d6animated.gif" );
            d6isrolling = true;
    }//GEN-LAST:event_d6ActionPerformed

    private void d8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d8ActionPerformed
       int numsides = 8;
            roll(numsides);
            outputBox.setText("" + numrolled);
            animate(D8.ii, D8.img, "/images/d8animated.gif" );
            d8isrolling = true;
    }//GEN-LAST:event_d8ActionPerformed

    private void d10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d10ActionPerformed
         int numsides = 10;
            roll(numsides);
            outputBox.setText("" + numrolled);
            animate(D10.ii, D10.img, "/images/d10animated.gif" );
            d10isrolling = true;
    }//GEN-LAST:event_d10ActionPerformed

    private void percentileDieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_percentileDieActionPerformed
         int numsides = 100;
            roll(numsides);
            outputBox.setText("" + numrolled);
            animate(PercentileDice.ii, PercentileDice.img, "/images/percentileanimated.gif" );
            percentileisrolling = true;
    }//GEN-LAST:event_percentileDieActionPerformed

    private void d12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d12ActionPerformed
       int  numsides = 12;
            roll(numsides);
            outputBox.setText("" + numrolled);
            animate(D12.ii, D12.img, "/images/d12animated.gif" );
            d12isrolling = true;
    }//GEN-LAST:event_d12ActionPerformed

    private void d20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d20ActionPerformed
        int numsides = 20;
            roll(numsides);
            outputBox.setText("" + numrolled);
           
            d20isrolling = true;
    }//GEN-LAST:event_d20ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
//        JFrame j = new JFrame("DICE");
//        j.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window().setVisible(true);
                ticks = 1;
                while (ticks >= 0 ){
                ticks++;
                if (ticks == 1000){
                   d4isrolling = false;
                   d6isrolling = false;
                   d8isrolling = false;
                   d10isrolling = false;
                   percentileisrolling = false;
                   d12isrolling = false;
                   d20isrolling = false;
                       ticks = 0;
                }
                }
                 if (d4isrolling == true){
                 animate(D4.ii, D4.img, "/images/d20animated.gif" );
                }
                
                 if (d6isrolling == true){
                 animate(D6.ii, D6.img, "/images/d20animated.gif" );
                }
                
                 if (d8isrolling == true){
                 animate(D8.ii, D8.img, "/images/d20animated.gif" );
                }
                
                 if (d10isrolling == true){
                 animate(D10.ii, D10.img, "/images/d20animated.gif" );
                }
                
                 if (percentileisrolling == true){
                 animate(PercentileDice.ii, PercentileDice.img, "/images/d20animated.gif" );
                }
                
                 if (d12isrolling == true){
                 animate(D12.ii, D12.img, "/images/d20animated.gif" );
                }
                
                 if (d20isrolling == true){
                 animate(D20.ii, D20.img, "/images/d20animated.gif" );
                }
                
                
                
                
              //  if ( d12ActionPerformed(evt) = true)
             // if (java.awt.event.ActionEvent evt)  )
            }
        });
    }
    
//     public static int roll(int numsides){
//         double divratio = 10 / numsides;
//         double rand = Math.random() * 10;
//         //for(int i = 0; i < numsides; i++){
//             int j = 0;
//             if (rand > divratio || rand < (divratio + 1)){
//                j = ((int) rand) +1;
//             }
//             else {
//             j = numsides;
//         }
//             numrolled = j;
//             System.out.println(numrolled);
//         //}
//         return numrolled;
//     }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton d10;
    private javax.swing.JButton d12;
    private javax.swing.JButton d20;
    private javax.swing.JButton d4;
    private javax.swing.JButton d6;
    private javax.swing.JButton d8;
    private javax.swing.JButton jButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea outputBox;
    private javax.swing.JButton percentileDie;
    // End of variables declaration//GEN-END:variables
}
